### ISSUE TITLE
Class.create

### ISSUE THREAD

**Issue by jamesplease** [marionettejs/backbone-metal#1]
Create a new instance w.o.o using the `new` keyword

pls

**Comment by jamiebuilds** [comment]
I looked into this before, and there isn't a performant way of doing this. 

http://jsperf.com/new-class-vs-class-create/2

**Comment by jamesplease** [comment]
I think create1 is good enough. This is a feature that people will want.

**Comment by jamiebuilds** [comment]
@jmeas that would require the `create` method to know the number of arguments.

**Comment by jamiebuilds** [comment]
Closing this, even the fastest option of using `Object.create` would be far too slow, and even slower when including even the simplest of polyfills.

http://jsperf.com/new-class-vs-class-create/4

**Comment by jamesplease** [comment]
u should add it

**Comment by jamiebuilds** [comment]
I don't see the benefit of it
