### ISSUE TITLE
Method & Hash collisions in Mixins

### ISSUE THREAD

**Issue by StevenLangbroek** [marionettejs/backbone-metal#10]
Right now I'm using [Cocktail](https://github.com/onsi/cocktail) for mixins, which has an extremely nice feature, which is critical to the way we use it: it merges hashes and functions. So a UI hash in your mixin will get merged into the UI hash on the class we're mixing into, and method will all get called in order without having to call `super`. Now, the downside is obviously that you can't override methods in your actual class. Curious as to what your thoughts on this are :).

Thanks!

**Comment by cmaher** [comment]
`super`, though you have to remember to call it, is far more flexible and powerful than automatic method chaining. It lets you choose when (or if) to call the super method. Though the api is slightly less convenient, the benefits are worth it. That said, `Class.mixin` would be the method to overwrite if you want this behavior.

**Comment by jamiebuilds** [comment]
This would break compatibility with Backbone's normal classes, and wouldn't be a well-defined behavior.
