### ISSUE TITLE
Rename backbone-metal to backbone.metal?

### ISSUE THREAD

**Issue by MasterLambaster** [marionettejs/backbone-metal#14]
Should we think on on renaming backbone-metal to backbone.metal to match all other components, like `backbone.radio`, `backbone.marionette` and `backbone.babysitter`

**Comment by jamiebuilds** [comment]
i'd rather not rename the package on npm. The naming scheme I use is:
- `backbone.class` if it exports a single class.
- `backbone-module` if it exports a number of things.
