### ISSUE TITLE
Class.prototype.destroy

### ISSUE THREAD

**Issue by jamiebuilds** [marionettejs/backbone-metal#18]
``` js
Class.prototype.destroy = function() {
  this.stopListening();
};
```

@marionettejs/marionette-core?

**Comment by jamesplease** [comment]
:+1: for something like this.

what's your reasoning behind not including a destroy event?

**Comment by paulfalgout** [comment]
I'm :+1: 

Correct me if I'm wrong, but metal doesn't trigger events.  It's more about inheritance over hooks.

**Comment by jamiebuilds** [comment]
> what's your reasoning behind not including a destroy event?

No particular reason, although the one tough thing is:

``` js
Class.prototype.destroy = function() {
  this.trigger('before:destroy', this);
  this.stopListening();
  this.trigger('destroy', this);
};

const MyClass = Class.extend({
  destroy() {
    this.doSomething();
    this._super();
  }
});

let myClass = new MyClass();
myClass.destroy();
// doSomething()           -- sucks trigger(before:destroy) happens after this
// trigger(before:destroy)
// stopListening()
// trigger(destroy)        -- and listenTo(destroy) won't work
```

**Comment by megawac** [comment]
Definitely :+1: for this, something I usually patch in myself

**Comment by jamesplease** [comment]
> // trigger(destroy)        -- and listenTo(destroy) won't work

Yeah, I dislike the `destroy` event for this reason. I only use `before:destroy` in my appz.

> // doSomething()           -- sucks trigger(before:destroy) happens after this

No counter-argument here :[ This does suck.

**Comment by jamiebuilds** [comment]
I just looked through our codebase and this was the only time a `destroy` event was used.

``` js
View.extend({
  constructor() {
    this.on({
      render: () => scrollTracker.start(),
      destroy: () => scrollTracker.stop(),
    });
    this._super(...arguments);
  }
})
```

I don't consider this a good use of events. I think it's better to override the normal methods and call super.

``` js
View.extend({
  render() {
    this._super(...arguments);
    scrollTracker.start();
  },
  destroy() {
    this._super(...arguments);
    scrollTracker.stop();
  }
})
```

I'm not sure I can think of a really good use case for outside objects listening for destroy.

**Comment by ianmstew** [comment]
@thejameskyle I have a use case for outside objects listening to `destroy`: https://github.com/Squareknot/marionette.state/blob/master/src/state.js#L87.  A dynamic object whose lifecycle is bound to another dynamic object.  The most obvious use case for this is an auxiliary object that attaches to a view, but is no longer needed once the view is destroyed.

**Comment by jamiebuilds** [comment]
Seems like an overlap in an object's lifecycle with a view's lifecycle, render/remove are (and should be) different than construct/destroy.

**Comment by ianmstew** [comment]
I want an auxiliary manager object to exist for exactly the length of the target view or another evented object, from construct all the way to destroy.

**Comment by jamiebuilds** [comment]
What about your view requires that? I don't see anything.

**Comment by ianmstew** [comment]
In my use case I have views that instantiate a state manager that encapsulates a state model and associated business logic.  This state manager sometimes listens to app-level events or entities, and therefore could be bound to a long-lived object outside of the view.  Because the state manager only serves the purposes of the view instance, the state manager needs to be cleaned up when the view is destroyed to prevent memory leaks.

``` js
var ViewWithState = Mn.ItemView.extend({
  stateEvents: {
    'change:active': 'onChangeActive'
  }
  initialize: function() {
    this.state = new Mn.State({
      component: this
    });
    this.bindEntityEvents(this.state.getModel(), this.stateEvents):
  },
  onChangeActive: (stateModel, active) {
    this.$el.addClass('active');
  }
});
```

**Comment by jamiebuilds** [comment]
I'm going to add the hook in place, if we want to add the trigger we can do that later.

**Comment by paulfalgout** [comment]
I'm :+1: on this without the triggers.  In `Mn` we'd probably want `triggerMethod` so we'd be adding this via `Marionette.Class` anyhow.

**Comment by jamiebuilds** [comment]
Moving to #21
