### ISSUE TITLE
Support old underscore

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone-metal#19]
Just to match Mn.

In testing the only thing keeping `1.4.4` from working is `_.noop`

It's so simple we could just shim it.. which would keep the tests working and the code pretty.. 

``` js
if (!_.isFunction(_.noop)) {
  _.noop = function(){};
}
```

or we could attach one to `Metal.noop`

The related test is: https://github.com/marionettejs/backbone-metal/blob/master/test/support.js#L115

Thoughts?

**Comment by jamiebuilds** [comment]
I would just replace:

``` js
var _warn = _console.warn || _console.log || _.noop;
```

with

``` js
var _warn = _console.warn || _console.log || function() {};
```

in https://github.com/marionettejs/backbone-metal/blob/master/src/backbone-metal.js#L468 and update the test to make sure it doesn't throw an error

**Comment by megawac** [comment]
Can you publish to npm svp

**Comment by jamiebuilds** [comment]
Published
