### ISSUE TITLE
Rename triggerMethod

### ISSUE THREAD

**Issue by jamesplease** [marionettejs/backbone-metal#3]
to `triggerClassEvent`.

`triggerMethod` is a terrible name. It conflates what is happening by trying to mix triggering the event with firing a method, but to anyone being introduced to Marionette it _just_ sounds like a method will be called.

`triggerClassEvent` adds a new abstraction, class events, which are something people can reason about. It's a new noun that distinguishes what is happening from when a regular event is triggered, which is a pretty important distinction.

Also, it's nice to think of Class Events as something on top of regular Events, which they are.

The effects of this change are great for users of all experiences of Marionette, too. It provides a language with which to describe these things. I don't want to talk about the 'events' that a Region has, because it has more than that. It has Class Events. This new name would be so great for the docs, too. Instead of "TriggerMethods" (lol), we could take advantage of the new abstraction.

**Comment by jamiebuilds** [comment]
Definitely agree that `triggerMethod` is a bad name, but I'm not in love with `triggerClassEvent` either. I'm not sure else what it'd be called though.

The other thought I had awhile back was to abstract the normal `trigger` to always call the method on an object as well.

``` js
Class.mixin({
  trigger() {
    var methodName = 'on' + event.replace(triggerSplitter, getEventName);
    var method = this[methodName];
    var result;

    // call the onMethodName if it exists
    if (_.isFunction(method)) {
      // pass all arguments, except the event name
      result = method.apply(this, args);
    }

    // trigger the event
    this._super.apply(this, arguments); // <<<<< CALL THE SUPER METHOD <<<<< 

    return result;
  }
})
```

**Comment by jamesplease** [comment]
I like that best, but overriding things is a path I'd be scared to go down.

**Comment by jamiebuilds** [comment]
What's your concern with it?

**Comment by jamesplease** [comment]
It will _probably_ be backwards compatible, but I like the idea of not needing to 'overwrite' Backbone's documentation to explain a new trigger. 

"Here's my library that introduces a whole bunch of new, backwards-compatible features. Oh, also, we modify one method on Backbone.Events. nbd though."

It's just makes for a nicer story to not overwrite anything.

**Comment by jamiebuilds** [comment]
I wouldn't modify it on the `Events` object itself. Just on `Metal.Class`.

**Comment by jamesplease** [comment]
Would `classify` yield the Events trigger when, say, you pass a Backbone.View in?

**Comment by jamiebuilds** [comment]
No, it would add the same behavior to every class.

**Comment by jamesplease** [comment]
Updating just the `trigger`s on the individual Classes and leaving out Events might actually be the most confusing of all possible options...

I'd think that you would want to ensure that mixing in Events also gives you back the modified trigger, as well.

**Comment by jamiebuilds** [comment]
If someone went out of their way to create a class that didn't extend from `Metal.Class` and mixed in `Backbone.Events`, why would they expect it to be calling other methods when they called `trigger`?

**Comment by jamesplease** [comment]
It requires knowledge that you're only overwriting _some_ of Backbone's things, which is slightly more complex than overwriting it everywhere or nothing. It seems like a potential source of confusion.

**Comment by jamiebuilds** [comment]
I think I'd prefer that over breaking a third party library though.

**Comment by jamesplease** [comment]
What do you mean? Which third party lib would break?

**Comment by jamiebuilds** [comment]
Since other libraries mix it into the prototype it could cause things to be called multiple times. Like Marionette would call the `onFoo` method twice with no way of patching the behavior because of the `triggerMethod` conflict.

**Comment by jamesplease** [comment]
Right. Yeah, my preference is never overwrite anything, which completely avoids these sorts of problems. ur lib tho'

**Comment by jamiebuilds** [comment]
I'm not sold on the idea either, I wanted to figure out the pros/cons of it though

**Comment by jamesplease** [comment]
Makes sense.

**Comment by jamiebuilds** [comment]
I removed triggerMethod from this library.

**Comment by jamesplease** [comment]
:+1:
