### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jamesplease** [marionettejs/backbone-metal#34]
https://github.com/marionettejs/backbone-metal/blob/master/src/mixin.js#L14

should that be `_.extend(this.prototype, protoProps);`?

**Comment by jamiebuilds** [comment]
Nope.

```
new Mixin({
  foo: 'foo'
});
// Mixin { foo: 'foo' }
```

**Comment by jamesplease** [comment]
[oic](https://github.com/marionettejs/backbone-metal/blob/master/src/class.js#L218-L222)
