### ISSUE TITLE
propTypes

### ISSUE THREAD

**Issue by jamiebuilds** [marionettejs/backbone-metal#36]
Thinking about adding React-like `propTypes` right now.

``` js
Metal.DEBUG = true;

var MyClass = Metal.Class.extend({
  propTypes: {
    foo: Metal.PropTypes.isRequired
  }
});

var myClass1 = new MyClass({
  foo: 'bar'
});
// Cool

var myClass2 = new MyClass({
  foop: 'bar'
});
// TypeError: "foo" is required.
```

This would be a DEBUG mode feature for development use.

Could potentially be a separate library for `PropTypes` definitions.

@marionettejs/marionette-core thoughts?

**Comment by jamesplease** [comment]
sounds cool
