### ISSUE TITLE
Mixins should support `super`

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone-metal#7]
It's important that mixins do not clobber the prototype object with a naive `_.extend`. It'd be better if instead, Mixins added themselves to the prototype chain in a way that property resolution first checked the mixin then delegated up the chain. This approach would allow `super` functionality ofcourse as well.

a visual for this would look like this:

``` js
MyView = Marionette.View.extend({
  onShow: => console.log('view')
})

M1 = Marionette.Mixin.create({
  onShow: {
    console.log('m1')
    this._super();
   }
})

M2 = Marionette.View.extend({
  onShow: {
    console.log('m2')
    this._super();
  }
})

MyView.mixin(M1).mixin(M2);

new MyView(); // log: m2, m1, view
```

```
{object properties} -> {m2 props} -> {m1 props} {myview props} -> {marionette view props} -> {backbone view props}
```

https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/mixin.js

**Comment by jamiebuilds** [comment]
Mixins do support `_super`.
https://github.com/marionettejs/backbone-metal/blob/master/test/class.js#L148-L180

**Comment by jasonLaster** [comment]
interesting, didn't see the `_wrapAll` call
