### ISSUE TITLE
TypeError: Illegal invocation when using Metal.deprecate

### ISSUE THREAD

**Issue by jridgewell** [marionettejs/backbone-metal#9]
[![Example](http://requirebin.com/badge.png)](http://requirebin.com/?gist=500332fcbe0ed40b7268)

It's because `console` methods need to have `console` as the context, and calling `deprecate._warn` doesn't do that.

**Comment by jamiebuilds** [comment]
Gah, didn't realize this since calling `console.log` without the `console` context works in Node.

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/pull/2459

**Comment by paulfalgout** [comment]
- [ ] Apply: https://github.com/marionettejs/backbone.marionette/commit/f6886c46aa19ede7f50a17dbfae2c6dafbd26706
